// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: ma_sn.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SNMAServiceClient is the client API for SNMAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SNMAServiceClient interface {
	InsertKVToSN(ctx context.Context, in *InsertKVRequest, opts ...grpc.CallOption) (*InsertKVResponse, error)
}

type sNMAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSNMAServiceClient(cc grpc.ClientConnInterface) SNMAServiceClient {
	return &sNMAServiceClient{cc}
}

func (c *sNMAServiceClient) InsertKVToSN(ctx context.Context, in *InsertKVRequest, opts ...grpc.CallOption) (*InsertKVResponse, error) {
	out := new(InsertKVResponse)
	err := c.cc.Invoke(ctx, "/proto.SNMAService/InsertKVToSN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SNMAServiceServer is the server API for SNMAService service.
// All implementations must embed UnimplementedSNMAServiceServer
// for forward compatibility
type SNMAServiceServer interface {
	InsertKVToSN(context.Context, *InsertKVRequest) (*InsertKVResponse, error)
	mustEmbedUnimplementedSNMAServiceServer()
}

// UnimplementedSNMAServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSNMAServiceServer struct {
}

func (UnimplementedSNMAServiceServer) InsertKVToSN(context.Context, *InsertKVRequest) (*InsertKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertKVToSN not implemented")
}
func (UnimplementedSNMAServiceServer) mustEmbedUnimplementedSNMAServiceServer() {}

// UnsafeSNMAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SNMAServiceServer will
// result in compilation errors.
type UnsafeSNMAServiceServer interface {
	mustEmbedUnimplementedSNMAServiceServer()
}

func RegisterSNMAServiceServer(s grpc.ServiceRegistrar, srv SNMAServiceServer) {
	s.RegisterService(&SNMAService_ServiceDesc, srv)
}

func _SNMAService_InsertKVToSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SNMAServiceServer).InsertKVToSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SNMAService/InsertKVToSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SNMAServiceServer).InsertKVToSN(ctx, req.(*InsertKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SNMAService_ServiceDesc is the grpc.ServiceDesc for SNMAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SNMAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SNMAService",
	HandlerType: (*SNMAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertKVToSN",
			Handler:    _SNMAService_InsertKVToSN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ma_sn.proto",
}
